let tableBody = [];

let tableDays = [
  "",
  "SATURDAY",
  "SUNDAY",
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
];

for (let x = 1; x < 8; x++) {
  let tableCells = [];

  for (let y = 1; y < 21; y++) {
    tableCells.push({
      period: y,
    });
  }

  tableBody.push({
    id: x,
    day: tableDays[x],
    cells: tableCells,
  });
}

let tableHeader = [
  { period: 0, time: "" },
  { period: 1, time: "8:00 - 8:30" },
  { period: 2, time: "8:30 - 9:00" },
  { period: 3, time: "9:00 - 9:30" },
  { period: 4, time: "9:30 - 10:00" },
  { period: 5, time: "10:00 - 10:30" },
  { period: 6, time: "10:30 - 11:00" },
  { period: 7, time: "11:00 - 11:30" },
  { period: 8, time: "11:30 - 12:00" },
  { period: 9, time: "12:00 - 12:30" },
  { period: 10, time: "12:30 - 1:00" },
  { period: 11, time: "1:00 - 1:30" },
  { period: 12, time: "1:30 - 2:00" },
  { period: 13, time: "2:00 - 2:30" },
  { period: 14, time: "2:30 - 3:00" },
  { period: 15, time: "3:00 - 3:30" },
  { period: 16, time: "3:30 - 4:00" },
  { period: 17, time: "4:00 - 4:30" },
  { period: 18, time: "4:30 - 5:00" },
  { period: 19, time: "5:00 - 5:30" },
  { period: 20, time: "5:30 - 6:00" },
];

export const ScheduleTableBody = tableBody;
export const ScheduleTableHeader = tableHeader;
export const BackendData = [
  {
    id: 0,
    day: "SATURDAY",
    startPeriod: 2,
    endPeriod: 4,
    englishName: "Maths 1",
    arabicName: "رياضيات 1",
    teacher: "Mr. Hbab",
    room: "Room 1",
    type: "LECTURE",
  },
  {
    id: 1,
    day: "SATURDAY",
    startPeriod: 2,
    endPeriod: 4,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab 2",
    room: "Room 4",
    type: "SECTION",
  },
  {
    id: 2,
    day: "SATURDAY",
    startPeriod: 5,
    endPeriod: 7,
    englishName: "Physics",
    arabicName: "فيزياء",
    teacher: "Mr. Hbab Physics",
    room: "Room 2",
    type: "LECTURE",
  },
  {
    id: 3,
    day: "SUNDAY",
    startPeriod: 3,
    endPeriod: 6,
    englishName: "Maths",
    arabicName: "رياضيات",
    teacher: "Mr. Hbab3",
    room: "Room 3",
  },
  {
    id: 3,
    day: "MONDAY",
    startPeriod: 1,
    endPeriod: 3,
    englishName: "Maths",
    arabicName: "رياضيات",
    teacher: "Mr. Hbab4",
    room: "Room 4",
  },
  {
    id: 4,
    day: "MONDAY",
    startPeriod: 4,
    endPeriod: 6,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab5",
    room: "Room 5",
  },
  {
    id: 5,
    day: "MONDAY",
    startPeriod: 7,
    endPeriod: 9,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab6",
    room: "Room 6",
  },
  {
    id: 6,
    day: "TUESDAY",
    startPeriod: 1,
    endPeriod: 3,
    englishName: "Maths",
    arabicName: "رياضيات",
    teacher: "Mr. Hbab7",
    room: "Room 7",
  },
  {
    id: 7,
    day: "TUESDAY",
    startPeriod: 4,
    endPeriod: 6,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab8",
    room: "Room 8",
  },
  {
    id: 8,
    day: "TUESDAY",
    startPeriod: 7,
    endPeriod: 9,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab9",
    room: "Room 9",
  },
  {
    id: 9,
    day: "WEDNESDAY",
    startPeriod: 1,
    endPeriod: 3,
    englishName: "Maths",
    arabicName: "رياضيات",
    teacher: "Mr. Hbab10",
    room: "Room 10",
  },
  {
    id: 10,
    day: "WEDNESDAY",
    startPeriod: 4,
    endPeriod: 6,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab11",
    room: "Room 11",
  },
  {
    id: 11,
    day: "WEDNESDAY",
    startPeriod: 7,
    endPeriod: 9,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab12",
    room: "Room 12",
  },
  {
    id: 12,
    day: "THURSDAY",
    startPeriod: 1,
    endPeriod: 3,
    englishName: "Maths",
    arabicName: "رياضيات",
    teacher: "Mr. Hbab13",
    room: "Room 13",
  },
  {
    id: 13,
    day: "THURSDAY",
    startPeriod: 4,
    endPeriod: 6,
    englishName: "English",
    arabicName: "اللغة الانجليزية",
    teacher: "Mr. Hbab14",
    room: "Room 14",
  },
];
