export const ProfessorsFormData = [
  {
    id: 0,
    title: "login.email",
    req: true,
    name: "email",
    type: "email",
    row: true,
  },
  {
    id: 1,
    title: "login.password",
    req: true,
    name: "password",
    type: "password",
    row: true,
  },
  {
    id: 2,
    title: "common.ar_name",
    name: "arabicName",
    req: true,
    type: "text",
    row: true,
  },
  {
    id: 3,
    title: "common.eng_name",
    name: "englishName",
    req: true,
    type: "text",
    row: true,
  },
  {
    id: 4,
    title: "professor.department",
    name: "department",
    req: true,
    type: "text",
    row: true,
    department: true,
  },
  // {
  //   id: 5,
  //   title: "professor.title",
  //   name: "title",
  //   type: "text",
  //   row: true,
  // },
];
