export const ScheduleData = [
  {
    id: "ef5a925b-8d0e-404e-ad75-1c8056e700ed",
    tableId: "3c1bee2d-98b3-443b-b574-58dad3d471ab",
    courseInstanceId: "23026360-a448-4584-b1c0-d78904f487b8",
    englishName: "General English",
    arabicName: "لفة الانجليزية",
    classType: "LECTURE",
    startPeriod: 2,
    endPeriod: 3,
    day: "TUESDAY",
  },
  {
    id: "ef5a925b-8d0e-404e-ad75-1c8056e700es",
    tableId: "3c1bee2d-98b3-443b-b574-58dad3d471ab",
    courseInstanceId: "23026360-a448-4584-b1c0-d78904f487b8",
    englishName: "Physics 1",
    arabicName: "فيزياء 1",
    classType: "LECTURE",
    startPeriod: 4,
    endPeriod: 6,
    day: "TUESDAY",
  },
  {
    id: "e2e89365-51d7-4939-aad1-64ad4e4153c2",
    tableId: "48845b55-9ba5-4598-8270-4c9ce4c08439",
    courseInstanceId: "3f0e35f9-5ecb-4477-847d-5ccb5e8eca44",
    englishName: "General Chemistry",
    arabicName: "الكيمياء العامة",
    classType: "LECTURE",
    startPeriod: 2,
    endPeriod: 4,
    day: "SATURDAY",
  },
  {
    id: "ef5a925b-8d0e-404e-ad75-1c8056e700ea",
    tableId: "3c1bee2d-98b3-443b-b574-58dad3d471ab",
    courseInstanceId: "23026360-a448-4584-b1c0-d78904f487b8",
    englishName: "Computer",
    arabicName: "الحاسب الالي",
    classType: "LECTURE",
    startPeriod: 7,
    endPeriod: 8,
    day: "THURSDAY",
  },
  {
    id: "ef5a925b-8d0e-404e-ad75-1c8056e700ex",
    tableId: "3c1bee2d-98b3-443b-b574-58dad3d471ab",
    courseInstanceId: "23026360-a448-4584-b1c0-d78904f487b8",
    englishName: "Engineering Drawing",
    arabicName: "رسم هندسي",
    classType: "LECTURE",
    startPeriod: 1,
    endPeriod: 4,
    day: "SUNDAY",
  },
];

export const StaffCourses = [
  {
    englishName: "General English",
    arabicName: "لغة انجليزية",
    id: "HUM101",
  },
  {
    englishName: "General Chemistry",
    arabicName: "الكيمياء العامة",
    id: "BSM012",
  },
  {
    englishName: "Physics 1",
    arabicName: "فيزياء 1",
    id: "BSM011",
  },
  {
    englishName: "Computer",
    arabicName: "الحاسب الالي",
    id: "BSM022",
  },
  {
    englishName: "Engineering Drawing",
    arabicName: "الرسم الهندسي",
    id: "BSM025",
  },
];

export const StaffStudentsData = [
  {
    courseId: "HUM101",
    students: [
      {
        studentId: "86420",
        arabicName: "احمد احمد محمد ",
        englishName: "Ahmed Ahmed Mohamed",
        notes: "-",
        classWork: "40",
        finalExam: "40",
        grade: "B",
        gpa: "3",
      },
      {
        studentId: "84621",
        arabicName: "احمد على محمد",
        englishName: "Ahmed Ali Mohamed",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86422",
        arabicName: "اسراء جمال محمد",
        englishName: "Esraa Gamal Mohamed",
        notes: "-",
        classWork: "45",
        finalExam: "45",
        grade: "B+",
        gpa: "3.3",
      },

      {
        studentId: "86423",
        arabicName: "اسراء شريف غريب",
        englishName: "Esraa Sherif Gharib",
        notes: "عدم حضور الميدترم",
        classWork: "15",
        finalExam: "40",
        grade: "D",
        gpa: "1.7",
      },

      {
        studentId: "86424",
        arabicName: "ساجد على رمضان",
        englishName: "Saged Ali Ramadan",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86425",
        arabicName: "ياسين محمد فاروق",
        englishName: "Yassin Mohamed Farouk",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86426",
        arabicName: "سلمى هادي رجب",
        englishName: "Salma Hady Ragab",
        notes: "عدم حضور الشفوي",
        classWork: "30",
        finalExam: "40",
        grade: "B-",
        gpa: "2.7",
      },
      {
        studentId: "86427",
        arabicName: "مينا سرور جورج",
        englishName: "Mina Sarour George",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86428",
        arabicName: "ماريا عيسى فريد",
        englishName: "Maria Essa Farid",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86429",
        arabicName: "محمد علي سيف",
        englishName: "Mohamed Ali Saif",
        notes: "-",
        classWork: "43",
        finalExam: "48",
        grade: "A-",
        gpa: "3.7",
      },
    ],
  },
  {
    courseId: "BSM012",
    students: [
      {
        studentId: "86420",
        arabicName: "احمد احمد محمد ",
        englishName: "Ahmed Ahmed Mohamed",
        notes: "-",
        classWork: "40",
        finalExam: "40",
        grade: "B",
        gpa: "3",
      },
      {
        studentId: "84621",
        arabicName: "احمد على محمد",
        englishName: "Ahmed Ali Mohamed",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86422",
        arabicName: "اسراء جمال محمد",
        englishName: "Esraa Gamal Mohamed",
        notes: "-",
        classWork: "45",
        finalExam: "45",
        grade: "B+",
        gpa: "3.3",
      },

      {
        studentId: "86423",
        arabicName: "اسراء شريف غريب",
        englishName: "Esraa Sherif Gharib",
        notes: "عدم حضور الميدترم",
        classWork: "15",
        finalExam: "40",
        grade: "D",
        gpa: "1.7",
      },

      {
        studentId: "86424",
        arabicName: "ساجد على رمضان",
        englishName: "Saged Ali Ramadan",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86425",
        arabicName: "ياسين محمد فاروق",
        englishName: "Yassin Mohamed Farouk",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86426",
        arabicName: "سلمى هادي رجب",
        englishName: "Salma Hady Ragab",
        notes: "عدم حضور الشفوي",
        classWork: "30",
        finalExam: "40",
        grade: "B-",
        gpa: "2.7",
      },
      {
        studentId: "86427",
        arabicName: "مينا سرور جورج",
        englishName: "Mina Sarour George",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86428",
        arabicName: "ماريا عيسى فريد",
        englishName: "Maria Essa Farid",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86429",
        arabicName: "محمد علي سيف",
        englishName: "Mohamed Ali Saif",
        notes: "-",
        classWork: "43",
        finalExam: "48",
        grade: "A-",
        gpa: "3.7",
      },
    ],
  },
  {
    courseId: "BSM011",
    students: [
      {
        studentId: "86420",
        arabicName: "احمد احمد محمد ",
        englishName: "Ahmed Ahmed Mohamed",
        notes: "-",
        classWork: "40",
        finalExam: "40",
        grade: "B",
        gpa: "3",
      },
      {
        studentId: "84621",
        arabicName: "احمد على محمد",
        englishName: "Ahmed Ali Mohamed",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86422",
        arabicName: "اسراء جمال محمد",
        englishName: "Esraa Gamal Mohamed",
        notes: "-",
        classWork: "45",
        finalExam: "45",
        grade: "B+",
        gpa: "3.3",
      },

      {
        studentId: "86423",
        arabicName: "اسراء شريف غريب",
        englishName: "Esraa Sherif Gharib",
        notes: "عدم حضور الميدترم",
        classWork: "15",
        finalExam: "40",
        grade: "D",
        gpa: "1.7",
      },

      {
        studentId: "86424",
        arabicName: "ساجد على رمضان",
        englishName: "Saged Ali Ramadan",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86425",
        arabicName: "ياسين محمد فاروق",
        englishName: "Yassin Mohamed Farouk",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86426",
        arabicName: "سلمى هادي رجب",
        englishName: "Salma Hady Ragab",
        notes: "عدم حضور الشفوي",
        classWork: "30",
        finalExam: "40",
        grade: "B-",
        gpa: "2.7",
      },
      {
        studentId: "86427",
        arabicName: "مينا سرور جورج",
        englishName: "Mina Sarour George",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86428",
        arabicName: "ماريا عيسى فريد",
        englishName: "Maria Essa Farid",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86429",
        arabicName: "محمد علي سيف",
        englishName: "Mohamed Ali Saif",
        notes: "-",
        classWork: "43",
        finalExam: "48",
        grade: "A-",
        gpa: "3.7",
      },
    ],
  },
  {
    courseId: "BSM022",
    students: [
      {
        studentId: "86420",
        arabicName: "احمد احمد محمد ",
        englishName: "Ahmed Ahmed Mohamed",
        notes: "-",
        classWork: "40",
        finalExam: "40",
        grade: "B",
        gpa: "3",
      },
      {
        studentId: "84621",
        arabicName: "احمد على محمد",
        englishName: "Ahmed Ali Mohamed",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86422",
        arabicName: "اسراء جمال محمد",
        englishName: "Esraa Gamal Mohamed",
        notes: "-",
        classWork: "45",
        finalExam: "45",
        grade: "B+",
        gpa: "3.3",
      },

      {
        studentId: "86423",
        arabicName: "اسراء شريف غريب",
        englishName: "Esraa Sherif Gharib",
        notes: "عدم حضور الميدترم",
        classWork: "15",
        finalExam: "40",
        grade: "D",
        gpa: "1.7",
      },

      {
        studentId: "86424",
        arabicName: "ساجد على رمضان",
        englishName: "Saged Ali Ramadan",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86425",
        arabicName: "ياسين محمد فاروق",
        englishName: "Yassin Mohamed Farouk",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86426",
        arabicName: "سلمى هادي رجب",
        englishName: "Salma Hady Ragab",
        notes: "عدم حضور الشفوي",
        classWork: "30",
        finalExam: "40",
        grade: "B-",
        gpa: "2.7",
      },
      {
        studentId: "86427",
        arabicName: "مينا سرور جورج",
        englishName: "Mina Sarour George",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86428",
        arabicName: "ماريا عيسى فريد",
        englishName: "Maria Essa Farid",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86429",
        arabicName: "محمد علي سيف",
        englishName: "Mohamed Ali Saif",
        notes: "-",
        classWork: "43",
        finalExam: "48",
        grade: "A-",
        gpa: "3.7",
      },
    ],
  },
  {
    courseId: "BSM025",
    students: [
      {
        studentId: "86420",
        arabicName: "احمد احمد محمد ",
        englishName: "Ahmed Ahmed Mohamed",
        notes: "-",
        classWork: "40",
        finalExam: "40",
        grade: "B",
        gpa: "3",
      },
      {
        studentId: "84621",
        arabicName: "احمد على محمد",
        englishName: "Ahmed Ali Mohamed",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86422",
        arabicName: "اسراء جمال محمد",
        englishName: "Esraa Gamal Mohamed",
        notes: "-",
        classWork: "45",
        finalExam: "45",
        grade: "B+",
        gpa: "3.3",
      },

      {
        studentId: "86423",
        arabicName: "اسراء شريف غريب",
        englishName: "Esraa Sherif Gharib",
        notes: "عدم حضور الميدترم",
        classWork: "15",
        finalExam: "40",
        grade: "D",
        gpa: "1.7",
      },

      {
        studentId: "86424",
        arabicName: "ساجد على رمضان",
        englishName: "Saged Ali Ramadan",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86425",
        arabicName: "ياسين محمد فاروق",
        englishName: "Yassin Mohamed Farouk",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86426",
        arabicName: "سلمى هادي رجب",
        englishName: "Salma Hady Ragab",
        notes: "عدم حضور الشفوي",
        classWork: "30",
        finalExam: "40",
        grade: "B-",
        gpa: "2.7",
      },
      {
        studentId: "86427",
        arabicName: "مينا سرور جورج",
        englishName: "Mina Sarour George",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86428",
        arabicName: "ماريا عيسى فريد",
        englishName: "Maria Essa Farid",
        notes: "-",
        classWork: "50",
        finalExam: "50",
        grade: "A",
        gpa: "4",
      },
      {
        studentId: "86429",
        arabicName: "محمد علي سيف",
        englishName: "Mohamed Ali Saif",
        notes: "-",
        classWork: "43",
        finalExam: "48",
        grade: "A-",
        gpa: "3.7",
      },
    ],
  },
];
