export const DatabaseCourses = [
  { id: 0, code: "bsm10", englishName: "Physics", arabicName: "الفيزياء" },
  { id: 1, code: "cce10", englishName: "Math", arabicName: "الرياضيات" },
  { id: 2, code: "ecc10", englishName: "Art", arabicName: "الاء" },
  { id: 3, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 4, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 5, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 6, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 7, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 8, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 9, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 10, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 11, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 12, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
  { id: 13, code: "aet10", englishName: "Volley", arabicName: "الفوولي" },
];
