export const DatabaseProgramCourses = [
  {
    id: 0,
    code: "bsm10",
    englishName: "testinggggggg",
    arabicName: "الفيزياء",
    level: 1,
    semester: "FIRST",
    // levelId: "0d60f91d-454e-428c-a4c0-8be0d5c43d2c",
    semester: "SECOND",
    creditHours: 3,
    prerequisites: [1, 2],
    courseType: "COMPULSORY",
  },
  {
    id: 1,
    code: "cce10",
    englishName: "Math",
    arabicName: "الرياضيات",
    level: 1,
    semester: "FIRST",
  },
  {
    id: 2,
    code: "ecc10",
    englishName: "Art",
    arabicName: "الفنون",
    level: 1,
    semester: "FIRST",
  },
  {
    id: 3,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: 1,
    semester: "FIRST",
  },
  {
    id: 4,
    code: "bsm10",
    englishName: "Physics",
    arabicName: "الفيزياء",
    level: 1,
    semester: "SECOND",
  },
  {
    id: 5,
    code: "cce10",
    englishName: "Math",
    arabicName: "الرياضيات",
    level: 1,
    semester: "SECOND",
  },
  {
    id: 6,
    code: "ecc10",
    englishName: "Art2",
    arabicName: "الفنون",
    level: 1,
    semester: "SECOND",
  },
  {
    id: 7,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: 1,
    semester: "SECOND",
  },
  {
    id: 8,
    code: "bsm10",
    englishName: "Physics",
    arabicName: "الفيزياء",
    level: 1,
    semester: "SECOND",
  },
  {
    id: 9,
    code: "cce10",
    englishName: "Math",
    arabicName: "الرياضيات",
    level: 1,
    semester: "SUMMER",
  },
  {
    id: 10,
    code: "ecc10",
    englishName: "Art",
    arabicName: "الفنون",
    level: 1,
    semester: "SUMMER",
  },
  {
    id: 11,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: 1,
    semester: "SUMMER",
  },
  {
    id: 12,
    code: "bsm10",
    englishName: "Physics",
    arabicName: "الفيزياء",
    level: 1,
    semester: "SUMMER",
  },
  {
    id: 13,
    code: "cce10",
    englishName: "Math22",
    arabicName: "الرياضيات",
    level: 2,
    semester: "FIRST",
  },
  {
    id: 14,
    code: "ecc10",
    englishName: "Art22",
    arabicName: "الفنون",
    level: 2,
    semester: "FIRST",
  },
  {
    id: 15,
    code: "aet10",
    englishName: "Volley22",
    arabicName: "الفوولي",
    level: 2,
    semester: "FIRST",
  },
  {
    id: 16,
    code: "bsm10",
    englishName: "Physics22",
    arabicName: "الفيزياء",
    level: 2,
    semester: "SECOND",
  },
  {
    id: 17,
    code: "cce10",
    englishName: "Math22",
    arabicName: "الرياضيات",
    level: 2,
    semester: "SECOND",
  },
  {
    id: 18,
    code: "ecc10",
    englishName: "Art22",
    arabicName: "الفنون",
    level: 2,
    semester: "SECOND",
  },
  {
    id: 19,
    code: "aet10",
    englishName: "Volley22",
    arabicName: "الفوولي",
    level: 2,
    semester: "SECOND",
  },
  {
    id: 20,
    code: "bsm10",
    englishName: "Physics22",
    arabicName: "الفيزياء",
    level: 2,
    semester: "SECOND",
  },
  {
    id: 21,
    code: "cce10",
    englishName: "Math22",
    arabicName: "الرياضيات",
    level: 2,
    semester: "SECOND",
  },
  {
    id: 22,
    code: "ecc10",
    englishName: "Art22",
    arabicName: "الفنون",
    level: 2,
    semester: "SUMMER",
  },
  {
    id: 23,
    code: "aet10",
    englishName: "Volley22",
    arabicName: "الفوولي",
    level: 2,
    semester: "SUMMER",
  },
  {
    id: 24,
    code: "bsm10",
    englishName: "Physics22",
    arabicName: "الفيزياء",
    level: 2,
    semester: "SUMMER",
  },
  {
    id: 25,
    code: "cce10",
    englishName: "Math22",
    arabicName: "الرياضيات",
    level: 2,
    semester: "SUMMER",
  },
  {
    id: 26,
    code: "ecc10",
    englishName: "Art22",
    arabicName: "الفنون",
    level: 2,
    semester: "SUMMER",
  },
  {
    id: 27,
    code: "aet10",
    englishName: "Volley33",
    arabicName: "الفوولي",
    level: 3,
    semester: "FIRST",
  },
  {
    id: 28,
    code: "bsm10",
    englishName: "Physics33",
    arabicName: "الفيزياء",
    level: 3,
    semester: "FIRST",
  },
  {
    id: 29,
    code: "cce10",
    englishName: "Math33",
    arabicName: "الرياضيات",
    level: 3,
    semester: "FIRST",
  },
  {
    id: 30,
    code: "ecc10",
    englishName: "Art33",
    arabicName: "الفنون",
    level: 3,
    semester: "FIRST",
  },
  {
    id: 31,
    code: "aet10",
    englishName: "Volley33",
    arabicName: "الفوولي",
    level: 3,
    semester: "SECOND",
  },
  {
    id: 32,
    code: "bsm10",
    englishName: "Physics33",
    arabicName: "الفيزياء",
    level: 3,
    semester: "SECOND",
  },
  {
    id: 33,
    code: "cce10",
    englishName: "Math33",
    arabicName: "الرياضيات",
    level: 3,
    semester: "SECOND",
  },
  {
    id: 34,
    code: "ecc10",
    englishName: "Art33",
    arabicName: "الفنون",
    level: 3,
    semester: "SECOND",
  },
  {
    id: 35,
    code: "aet10",
    englishName: "Volley33",
    arabicName: "الفوولي",
    level: 3,
    semester: "SECOND",
  },
  {
    id: 36,
    code: "bsm10",
    englishName: "Physics33",
    arabicName: "الفيزياء",
    level: 3,
    semester: "SUMMER",
  },
  {
    id: 37,
    code: "cce10",
    englishName: "Math33",
    arabicName: "الرياضيات",
    level: 3,
    semester: "SUMMER",
  },
  {
    id: 38,
    code: "ecc10",
    englishName: "Art33",
    arabicName: "الفنون",
    level: 3,
    semester: "SUMMER",
  },
  {
    id: 39,
    code: "aet10",
    englishName: "Volley33",
    arabicName: "الفوولي",
    level: 3,
    semester: "SUMMER",
  },
];
