export const DatabaseProgramCourses = [
  {
    id: 0,
    code: "bsm10",
    englishName: "Physics",
    arabicName: "الفيزياء",
    level: 1,
    semester: "FIRST",
  },
  {
    id: 1,
    code: "cce10",
    englishName: "Math",
    arabicName: "الرياضيات",
    level: "",
    semester: "",
  },
  {
    id: 2,
    code: "ecc10",
    englishName: "Art",
    arabicName: "الاء",
    level: "",
    semester: "",
  },
  {
    id: 3,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 4,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 5,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 6,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 7,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 8,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 9,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 10,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 11,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 12,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
  {
    id: 13,
    code: "aet10",
    englishName: "Volley",
    arabicName: "الفوولي",
    level: "",
    semester: "",
  },
];
